# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 5901, host: 15901
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", path: "provision.sh"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "4096"
   end
end
